version: '3'
services:
    iotserver:
      image: registry.gitlab.com/andileeb/iotserverregistry/iotserver:0.2.28
      ports:
        - "9090:9000"
      expose:
        - "1883"
        - "5432"
      volumes:
        - ./config/iotserver/:/config/iotserver/
      depends_on:
        - iotserverbroker
        - iotserverdb
      networks:
        - bridge-net
      restart: on-failure
    iotserverbroker:
      image: registry.gitlab.com/andileeb/iotserverregistry/iotserverbroker:0.0.1
      ports:
        - "1883:1883"
        - "18083:18083"
        - "4200:8083"
      environment:
        - EMQ_LOADED_PLUGINS=emq_auth_pgsql,emq_modules,emq_recon,emq_retainer,emq_dashboard
        - EMQ_MQTT__ALLOW_ANONYMOUS=false
       # - EMQ_MQTT__ACL_NOMATCH=allow
       # - EMQ_MQTT__ACL_FILE=etc/acl.conf
        - EMQ_AUTH__PGSQL__SERVER=iotserverdb:5432
        - EMQ_AUTH__PGSQL__POOL=8
        - EMQ_AUTH__PGSQL__USERNAME=postgres
        - EMQ_AUTH__PGSQL__PASSWORD=password
        - EMQ_AUTH__PGSQL__PASSWORD_HASH=plain
        - EMQ_AUTH__PGSQL__DATABASE=postgres
        - EMQ_AUTH__PGSQL__AUTH_QUERY=select password from mqtt_user where username = '%u' limit 1
        - EMQ_AUTH__PGSQL__ACL_QUERY=select allow, ipaddr, username, clientid, access, topic from mqtt_acl where ipaddr = '%a' or username = '%u' or username = '${all}' or clientid = '%c'
      networks:
        - bridge-net
      restart: on-failure
    iotserverdb:
      image: registry.gitlab.com/andileeb/iotserverregistry/iotserverdb:0.1.3
      ports:
        - "5432:5432"
      volumes:
       - ./data/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
      networks:
        - bridge-net
      restart: on-failure
    iotserverruly:
      image: registry.gitlab.com/andileeb/iotserverregistry/iotserverruly:1.1.3
      expose:
        - "1883"
      volumes:
        - ./config/iotserverruly/:/rules
      networks:
        - bridge-net
      restart: on-failure
    iotserverntp:
      image: registry.gitlab.com/andileeb/iotserverregistry/iotserverntp:1.0.0
      ports:
        - "4222:123/udp"
      cap_add:
        - SYS_NICE
        - SYS_RESOURCE
        - SYS_TIME
      networks:
        - bridge-net
      restart: on-failure
    pgadmin:
      image: dpage/pgadmin4
      ports:
        - "7777:80"
      environment:
        - PGADMIN_DEFAULT_EMAIL=andreas.b.leeb@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=SuperSecret
      networks:
        - bridge-net
      restart: on-failure
    iotweather:
      image: eschaechl/weatherservice-nodejs:1.0.5
      networks:
        - bridge-net
    iotwebclient:
      image: juliankaindl/iot-webclient:3d
      ports:
        - "80:80"
      networks:
        - bridge-net
    # iotservernats:
    #   image: registry.gitlab.com/andileeb/iotserverregistry/iotservernats:0.0.1
    #   ports:
    #     - "4222:4222"
    #     - "6222:6222"
    #     - "8222:8222"
    #   networks:
    #     - bridge-net
    #   command: ["--auth", "3zdh59oahf62tdgeh65sf23h"]
    #   restart: on-failure
    # openhab:
    #   image: "openhab/openhab:2.3.0-amd64-debian"
    #   ports:
    #     - "8080:8080"
    #    expose:
    #     - "1883"
    #   volumes:
    #     - "./config/openhab/etc/localtime:/etc/localtime:ro"
    #     - "./config/openhab/etc/timezone:/etc/timezone:ro"
    #     - "./config/openhab/openhab_addons:/openhab/addons"
    #     - "./config/openhab/openhab_conf:/openhab/conf"
    #     - "./config/openhab/openhab_userdata:/openhab/userdata"
    #   environment:
    #     - OPENHAB_HTTP_PORT: "8080"
    #   networks:
    #     - bridge-net
    #   restart: always
networks:
  bridge-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16